# Generated by Django 5.2.1 on 2025-06-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
