# Generated by Django 5.2.1 on 2025-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(help_text='The name of the RFQ channel (e.g., WhatsApp, Email)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'RFQ Channel',
                'verbose_name_plural': 'RFQ Channels',
            },
        ),
    ]
