# Generated by Django 5.2.1 on 2025-07-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqchannels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqchannel',
            name='channel_name',
            field=models.CharField(blank=True, help_text='The name of the RFQ channel (e.g., WhatsApp, Email)', max_length=100, null=True, unique=True),
        ),
    ]
