# Generated by Django 5.2.1 on 2025-07-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0003_quotation_next_followup_date'),
        ('series', '0002_numberseries_delete_series'),
        ('team', '0002_alter_teammember_designation_alter_teammember_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('Delivery Pending', 'Delivery Pending'), ('Delivered', 'Delivered')], default='Delivery Pending', max_length=20)),
                ('signed_delivery_note', models.FileField(blank=True, null=True, upload_to='delivery_notes/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job_execution.deliverynote')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=50, unique=True)),
                ('date_received', models.DateField()),
                ('exp_date_completion', models.DateField(blank=True, null=True)),
                ('onsite_lab', models.CharField(choices=[('Onsite', 'Onsite'), ('Lab', 'Lab')], default='Onsite', max_length=20)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('site_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('Processing', 'Processing'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Delivered', 'Delivered'), ('Closed', 'Closed')], default='Processing', max_length=20)),
                ('work_order_type', models.CharField(choices=[('single', 'Single'), ('split', 'Split')], default='single', max_length=20)),
                ('certificate_label', models.CharField(blank=True, choices=[('Certificate', 'Certificate'), ('UUT Label', 'UUT Label')], max_length=50, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
                ('uuc_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to='team.teammember')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.purchaseorder')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.numberseries')),
            ],
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_execution.workorder'),
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job_execution.workorder')),
            ],
        ),
    ]
