# Generated by Django 5.2.1 on 2025-06-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('attention', models.CharField(blank=True, max_length=255, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(max_length=50)),
                ('IBAN', models.CharField(blank=True, max_length=34, null=True)),
                ('bank_address', models.TextField()),
                ('company_address', models.TextField()),
                ('po_number', models.CharField(max_length=100)),
                ('vat_no', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('rev_no', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rfqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('rfq_channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Number', 'Number'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.rfq')),
            ],
        ),
    ]
