# Generated by Django 5.2.1 on 2025-06-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='rfq_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
