# Generated by Django 5.2.1 on 2025-06-25 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqitem',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='rfq',
            name='assign_to',
            field=models.CharField(choices=[('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin'), ('User', 'User')], default='User', max_length=50),
        ),
        migrations.AddField(
            model_name='rfq',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed')], default='Processing', max_length=50),
        ),
    ]
