# Generated by Django 5.2.1 on 2025-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_alter_rfq_rfq_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('rfq_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('attention_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attention_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('attention_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFQChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rfq',
            name='attention_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
