# Generated by Django 5.2.1 on 2025-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_alter_client_address_alter_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Completed', 'Completed')], default='Processing', max_length=20, null=True),
        ),
    ]
