# Generated by Django 5.2.1 on 2025-07-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0003_rfq_current_status'),
        ('series', '0002_numberseries_delete_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='rfq_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.numberseries'),
        ),
    ]
