# Generated by Django 5.2.1 on 2025-07-02 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0003_alter_teammember_email'),
        ('rfq', '0003_client_rfqchannel_alter_rfq_attention_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Team.teammember')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.rfq')),
            ],
        ),
    ]
