# Generated by Django 5.2.1 on 2025-07-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0004_alter_teammember_email'),
        ('rfq', '0004_rfqitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqitem',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='due_date',
        ),
        migrations.AddField(
            model_name='rfq',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Team.teammember'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
