# Generated by Django 5.2.1 on 2025-07-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0004_rfq_rfq_no_rfq_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
