# Generated by Django 5.2.1 on 2025-07-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0005_rfqitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='client_po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='is_quotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfq',
            name='latest_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='po_file',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='when_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('PO Created', 'PO Created')], default='Processing', max_length=20, null=True),
        ),
    ]
