# Generated by Django 5.2.1 on 2025-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0007_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='client_po_number',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='is_quotation',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='latest_remarks',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='po_file',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='quotation_no',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='when_approved',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='rfq',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Completed', 'Completed')], default='Processing', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
