# Generated by Django 5.2.1 on 2025-07-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0008_remove_purchaseorderitem_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='reference',
        ),
    ]
