# Generated by Django 5.2.1 on 2025-07-23 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0009_remove_client_reference_remove_rfq_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqitem',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='attention_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Invalid phone number format.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Invalid phone number format.')]),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='attention_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Invalid phone number format.')]),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Invalid phone number format.')]),
        ),
    ]
