# Generated by Django 5.2.1 on 2025-07-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0010_remove_rfqitem_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='attention_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='attention_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
