# Generated by Django 5.2.1 on 2025-07-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0011_rfqitem_product_name_alter_client_attention_phone_and_more'),
        ('series', '0003_numberseries_series_numb_prefix_a8fe4b_idx'),
        ('team', '0002_alter_teammember_designation_alter_teammember_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='address',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='attention_email',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='attention_name',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='attention_phone',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfq',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.client'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name', 'email'], name='rfq_client_company_0e70b1_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['rfq_no', 'created_at'], name='rfq_rfq_rfq_no_243427_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqchannel',
            index=models.Index(fields=['channel_name'], name='rfq_rfqchan_channel_536c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqitem',
            index=models.Index(fields=['item_name'], name='rfq_rfqitem_item_na_85e7c2_idx'),
        ),
    ]
