# Generated by Django 5.2.1 on 2025-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0012_remove_rfq_address_remove_rfq_attention_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='rfq_client_company_0e70b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='rfq',
            name='rfq_rfq_rfq_no_243427_idx',
        ),
        migrations.RemoveIndex(
            model_name='rfqchannel',
            name='rfq_rfqchan_channel_536c1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='rfqitem',
            name='rfq_rfqitem_item_na_85e7c2_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='client',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='rfq',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='attention_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='attention_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='attention_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
