# Generated by Django 5.2.1 on 2025-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='Unknown Item', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
