# Generated by Django 5.2.1 on 2025-07-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_delete_unit_rename_price_item_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
