# Generated by Django 5.2.1 on 2025-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50, unique=True)),
                ('current_sequence', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
