# Generated by Django 5.2.1 on 2025-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_numberseries_delete_series'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='numberseries',
            index=models.Index(fields=['prefix'], name='series_numb_prefix_a8fe4b_idx'),
        ),
    ]
