# Generated by Django 5.2.1 on 2025-07-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_numberseries_series_numb_prefix_a8fe4b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='numberseries',
            name='series_numb_prefix_a8fe4b_idx',
        ),
    ]
