# Generated by Django 5.2.1 on 2025-07-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
        ('rfq', '0005_rfqitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='current_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='latest_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='when_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='attention_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfq.rfq'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_po_number', models.CharField(blank=True, max_length=50)),
                ('order_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], max_length=20)),
                ('po_file', models.FileField(blank=True, null=True, upload_to='purchase_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='quotation.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.purchaseorder')),
            ],
        ),
    ]
