# Generated by Django 5.2.1 on 2025-07-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotation_current_status_quotation_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
