# Generated by Django 5.2.1 on 2025-07-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotation_next_followup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product_name',
        ),
    ]
