# Generated by Django 5.2.1 on 2025-07-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_purchaseorderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='client_po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_file',
            field=models.FileField(blank=True, null=True, upload_to='po_files/'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation'),
        ),
    ]
