# Generated by Django 5.2.1 on 2025-07-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_purchaseorder_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='client_po_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_file',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='quotation.quotation'),
        ),
    ]
