# Generated by Django 5.2.1 on 2025-07-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation of the team member', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the team member', max_length=100, null=True, unique=True),
        ),
    ]
