# Generated by Django 5.2.1 on 2025-07-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(help_text='email of the team member'),
            preserve_default=False,
        ),
    ]
