# Generated by Django 5.2.1 on 2025-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_teammember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(help_text='email of the team member', max_length=100, unique=True),
        ),
    ]
